### ISSUE TITLE
修改资料闪退

### ISSUE THREAD

**Issue by mpasr** [CoderDwang/DWAddressBook#1]
！！！

**Comment by CoderDwang** [comment]
能否详细的说一下

**Comment by CoderDwang** [comment]
@mpasr 能否详细的说一下

**Comment by mpasr** [comment]
这里任何一项都点不了，点了就闪退。
发自我的 iPhone

**Comment by mpasr** [comment]
IPhone 7  10.3.3

发自我的 iPhone

**Comment by CoderDwang** [comment]
@mpasr 你好 ，我在模拟器与真机都进行了测试。获取手机号与联系人名称并没有出现奔溃的问题。可以加群：577506623，群内有众多开发者，可以一起解答问题。
![123](https://user-images.githubusercontent.com/15830996/33061768-3b4266cc-ced8-11e7-8ca6-86afb3ca4f78.gif)

**Comment by mpasr** [comment]
不是获取联系人啊，是修改资料啊

发自我的 iPhone

**Comment by CoderDwang** [comment]
@mpasr 可是我做的这个主要就是获取联系人啊

**Comment by mpasr** [comment]
不好意思 回复错了

发自我的 iPhone
